SIM_DIR="/nfs/dust/cms/user/beinsam/CommonNtuples/MC_SM"
NEW_SIM_DIR="/pnfs/desy.de/cms/tier2/store/user/sbein/CommonNtuples"
NEWEST_SIM_DIR="/pnfs/desy.de/cms/tier2/store/user/sbein/NtupleHub/Production2016v1"
BG_TYPES=(QCD DYJetsToLL WJetsToLNu ZJetsToNuNu WZZ WWZ WW WZ ZZZ ZZ TTWJetsToLNu)
#BG_TYPES=(WJetsToLNu)
RARE=(WZZ WWZ ZZZ)
DiBoson=(WZ WW ZZ)
MAD_HT_SPLIT_TYPES=(TTJets)
#MAD_HT_SPLIT_TYPES=()
WORK_DIR="/tmp"
CMS_WD="/afs/desy.de/user/n/nissanuv/cms-tools/CMSSW_8_0_5_patch1/src"
BG_WD="/afs/desy.de/user/n/nissanuv/cms-tools/bg"
SIM_DIR="/afs/desy.de/user/n/nissanuv/cms-tools/sim_x10x20x10"
#ANALYZER_PATH="/afs/desy.de/user/n/nissanuv/cms-tools/analysis/scripts/analyzer_x1x2x1.py"
ANALYZER_PATH="/afs/desy.de/user/n/nissanuv/cms-tools/analysis/scripts/analyzer_x1x2x1.py"
SCRIPTS_WD="${BG_WD}/scripts"
OUTPUT_DIR="${BG_WD}/output"
STD_OUTPUT="${OUTPUT_DIR}/stdoutput"
ERR_OUTPUT="${OUTPUT_DIR}/stderr"
FILE_OUTPUT="${OUTPUT_DIR}/single"